services:
  postgres:
    image: postgres:16-alpine
    container_name: syncra_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - syncra_net
    restart: unless-stopped

  postgres_test:
    image: postgres:16-alpine
    container_name: syncra_postgres_test
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5533:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_TEST} -d ${POSTGRES_DB_TEST}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - syncra_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncra_backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - syncra_net

volumes:
  postgres_data:
  postgres_test_data:

networks:
  syncra_net:
    driver: bridge