"""add core domain tables

Revision ID: c7bc4cfde008
Revises: 286ac7726930
Create Date: 2026-07-24 22:48:15.754263

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7bc4cfde008"
down_revision: Union[str, Sequence[str], None] = "286ac7726930"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("invite_code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_team_invite_code"), "team", ["invite_code"], unique=True)
    op.create_table(
        "meeting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "CANCELLED",
                "COMPLETED",
                name="meetingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meeting_author_id"), "meeting", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_starts_at"), "meeting", ["starts_at"], unique=False
    )
    op.create_index(op.f("ix_meeting_team_id"), "meeting", ["team_id"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "IN_PROGRESS", "DONE", name="taskstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_assignee_id"), "task", ["assignee_id"], unique=False)
    op.create_index(op.f("ix_task_due_date"), "task", ["due_date"], unique=False)
    op.create_index(op.f("ix_task_team_id"), "task", ["team_id"], unique=False)
    op.create_table(
        "team_member",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    op.create_table(
        "evaluation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("manager_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_evaluation_employee_id"), "evaluation", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_manager_id"), "evaluation", ["manager_id"], unique=False
    )
    op.create_table(
        "meeting_participant",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meeting.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("meeting_id", "user_id"),
    )
    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum("USER", "MANAGER", "ADMIN", name="userrole", native_enum=False),
            nullable=False,
        ),
    )
    op.drop_column("user", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_column("user", "role")
    op.drop_table("meeting_participant")
    op.drop_index(op.f("ix_evaluation_manager_id"), table_name="evaluation")
    op.drop_index(op.f("ix_evaluation_employee_id"), table_name="evaluation")
    op.drop_table("evaluation")
    op.drop_table("team_member")
    op.drop_index(op.f("ix_task_team_id"), table_name="task")
    op.drop_index(op.f("ix_task_due_date"), table_name="task")
    op.drop_index(op.f("ix_task_assignee_id"), table_name="task")
    op.drop_table("task")
    op.drop_index(op.f("ix_meeting_team_id"), table_name="meeting")
    op.drop_index(op.f("ix_meeting_starts_at"), table_name="meeting")
    op.drop_index(op.f("ix_meeting_author_id"), table_name="meeting")
    op.drop_table("meeting")
    op.drop_index(op.f("ix_team_invite_code"), table_name="team")
    op.drop_table("team")
    # ### end Alembic commands ###
