"""add title to meeting

Revision ID: 2801d5bb1d6e
Revises: c7bc4cfde008
Create Date: 2026-07-25 23:19:21.673385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2801d5bb1d6e'
down_revision: Union[str, Sequence[str], None] = 'c7bc4cfde008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comment_author_id'), 'task_comment', ['author_id'], unique=False)
    op.create_index(op.f('ix_task_comment_task_id'), 'task_comment', ['task_id'], unique=False)
    op.add_column('meeting', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'title')
    op.drop_index(op.f('ix_task_comment_task_id'), table_name='task_comment')
    op.drop_index(op.f('ix_task_comment_author_id'), table_name='task_comment')
    op.drop_table('task_comment')
    # ### end Alembic commands ###
